version: "3"
services:
  web:
    image: nginx:1.13.5-alpine
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./data:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    links:
      - app
  app:
    image: php:7-fpm-alpine3.8
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-fpm
    tty: true
    ports:
      - 9000:9000
    volumes:
      - ./data:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
